[package]
name = "jeremy-rust-scripts"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
dirs = "4.0.0"
duct = "1.1.0"
exec = "0.3"

[[bin]]
name = "_colorscheme"

[[bin]]
name = "_jeremy-post-install"

[[bin]]
name = "_jeremy-shell-init"

[[bin]]
name = "_ssh-ghostty"
